### PR TITLE
Fx typo: variable valueSift -> valueShift

### PR DESCRIPTION
**Pull request by Anton-Latukha**

### CODE REVIEW

**Review by raphaelcohn — APPROVED** [review]
Thank you very much! This is a superb spot in one of the less used parts of shellfire.

**Comment by Anton-Latukha** [comment]
It was after dependency declarations in flattened application, described shellfire-dev/fatten#2
While I thought that `valueSift` is funny & obviously closely reassembles something more serious.

Happy to help improve. I am totally blasted that all this creation works, and how it works. And more over that it works in my hands.

**Comment by Anton-Latukha** [comment]
By the way, maybe you know.
Costa Tsaousis from firehol/netdata showed me this beauty: megastep/makeself.

Probably you know about each other.

**Comment by raphaelcohn** [comment]
I don't - thanks for the suggestion. It would make a nice alternative to fatten. I've worked with shell archivers before in the distant past. They can be a bit picky. One to think about for sure.

**Pull request merged**
